# Generated by Django 2.1.3 on 2019-07-17 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FichaConductor',
            fields=[
                ('rut', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('pNombre', models.CharField(max_length=30)),
                ('sNombre', models.CharField(max_length=30)),
                ('apPaterno', models.CharField(max_length=30)),
                ('apMaterno', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('fNacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=9)),
                ('licencia', models.FileField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Tvehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipovehiculo', models.CharField(choices=[('Auto', 'CyC L'), ('Auto', 'CyC XL')], max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='fichaconductor',
            name='Vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conductor.Tvehiculo'),
        ),
    ]
