# Generated by Django 2.1.2 on 2019-07-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvehiculo',
            name='tipovehiculo',
            field=models.CharField(choices=[('1', 'CyC L'), ('2', 'CyC XL')], max_length=15),
        ),
    ]
