# Generated by Django 2.1.2 on 2019-07-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductor', '0002_auto_20190718_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvehiculo',
            name='tipovehiculo',
            field=models.CharField(choices=[('Auto', 'CyC L'), ('Van', 'CyC XL')], max_length=15),
        ),
    ]
