# Generated by Django 2.1.3 on 2019-07-18 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conductor', '0003_auto_20190718_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tlicencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipolicencia', models.CharField(choices=[('Tipo', 'Tipo de licencia: A'), ('Tipo', 'Tipo de licencia: B')], max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='fichaconductor',
            name='licencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conductor.Tlicencia'),
        ),
    ]
