# Generated by Django 2.1.3 on 2019-07-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductor', '0004_auto_20190718_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlicencia',
            name='tipolicencia',
            field=models.CharField(choices=[('Licencia A', 'Tipo de licencia: A'), ('Licencia B', 'Tipo de licencia: B')], max_length=15),
        ),
    ]
