# Generated by Django 2.1.3 on 2019-07-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductor', '0005_auto_20190718_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlicencia',
            name='tipolicencia',
            field=models.CharField(choices=[('Licencia A', 'A'), ('Licencia B', 'B')], max_length=15),
        ),
    ]
