# Generated by Django 2.1.2 on 2019-07-19 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conductor', '0006_auto_20190718_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaconductor',
            name='Usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
