# Generated by Django 2.1.2 on 2019-07-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=20, max_digits=50)),
                ('lng', models.DecimalField(decimal_places=20, max_digits=50)),
            ],
        ),
    ]
