# Generated by Django 2.1.2 on 2019-07-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='fecha',
            field=models.DateField(auto_now_add=True, default='2019-03-20'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='hora',
            field=models.TimeField(auto_now_add=True, default='13:01'),
            preserve_default=False,
        ),
    ]
