# Generated by Django 2.1.2 on 2019-07-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20190723_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='UbicacionFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=20, max_digits=50)),
                ('lng', models.DecimalField(decimal_places=20, max_digits=50)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
