# Generated by Django 2.1.3 on 2019-07-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canal',
            name='tipoCanal',
            field=models.CharField(choices=[('Casa', 'Interno'), ('depa', 'Externo'), ('ajja', 'Go')], max_length=15),
        ),
    ]
